
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Mettez à jour ces valeurs avec les informations de votre nouvelle base de données
const SUPABASE_URL = "https://syfphnbfwisnimeacvnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5ZnBobmJmd2lzbmltZWFjdm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMzMxNDYsImV4cCI6MjA1NzYwOTE0Nn0.d617CTnEUNgLRwwq47TnLM2GjksrYgD71YFgz20TU9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
